// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8oFC4UEHCF4czVwOV8_ajHCs6SZU3HOA',
    appId: '1:582739384174:web:dbecc4c2cd993f8e00537f',
    messagingSenderId: '582739384174',
    projectId: 'testingproj-187cc',
    authDomain: 'testingproj-187cc.firebaseapp.com',
    storageBucket: 'testingproj-187cc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTMUyZA2PwsbpPzyUBcxvrkkduJ6qCSAQ',
    appId: '1:582739384174:android:6e220390a7d368a700537f',
    messagingSenderId: '582739384174',
    projectId: 'testingproj-187cc',
    storageBucket: 'testingproj-187cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3LUQmigXjZqPahBll1Cj9NHTdvj8Kt4A',
    appId: '1:582739384174:ios:798f82f3c2a1871d00537f',
    messagingSenderId: '582739384174',
    projectId: 'testingproj-187cc',
    storageBucket: 'testingproj-187cc.firebasestorage.app',
    iosBundleId: 'com.example.testingproj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3LUQmigXjZqPahBll1Cj9NHTdvj8Kt4A',
    appId: '1:582739384174:ios:798f82f3c2a1871d00537f',
    messagingSenderId: '582739384174',
    projectId: 'testingproj-187cc',
    storageBucket: 'testingproj-187cc.firebasestorage.app',
    iosBundleId: 'com.example.testingproj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8oFC4UEHCF4czVwOV8_ajHCs6SZU3HOA',
    appId: '1:582739384174:web:563199a5211474eb00537f',
    messagingSenderId: '582739384174',
    projectId: 'testingproj-187cc',
    authDomain: 'testingproj-187cc.firebaseapp.com',
    storageBucket: 'testingproj-187cc.firebasestorage.app',
  );
}
